
CREATE TABLE SYSTEM_EVENTS (
 EVENT_ID NUMBER,
 EVENT_CODE VARCHAR2(10) NOT NULL,
 EVENT_DESCIPTION VARCHAR2(200),
 EVENT_TIME DATE NOT NULL,
 CONSTRAINT PK_EVENT_ID PRIMARY KEY(EVENT_ID))
 ORGANIZATION INDEX;

INSERT INTO SYSTEM_EVENTS VALUES(9, 'EVNT-A1-10', 'Critical', '01-JAN-2017');
INSERT INTO SYSTEM_EVENTS VALUES(1, 'EVNT-C1-09', 'Warning', '01-JAN-2017');
INSERT INTO SYSTEM_EVENTS VALUES(7, 'EVNT-E1-14', 'Critical', '01-JAN-2017');

commit;


CREATE TABLE IDENTITY_TST (COL1 NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 100
INCREMENT BY 10), COL2 VARCHAR2(30));

INSERT INTO IDENTITY_TST(COL2) VALUES('A');
INSERT INTO IDENTITY_TST(COL1, COL2) VALUES(DEFAULT, 'B');

CREATE TABLE clob_data_table (
    id       INTEGER PRIMARY KEY,
    clob_data CLOB
);

DECLARE
    large_text CLOB;
    i          INTEGER := 1;
BEGIN
    DBMS_LOB.createtemporary(large_text, TRUE);

    WHILE i <= 5000 LOOP
        DBMS_LOB.writeappend(large_text, LENGTH('Sentence ' || i || ' of the long text ' || i || '. '), 'Sentence ' || i || ' of the long text ' || i || '. ');
        i := i + 1;
    END LOOP;
        INSERT INTO clob_data_table (id, clob_data) VALUES (1, TO_CLOB(large_text));

 -- Commit the transaction
    COMMIT;
END;
/



-- Creating the procedure
CREATE OR REPLACE PROCEDURE get_employee_data IS
    -- Declare variables to hold employee data
    v_employee_id   employees.employee_id%TYPE;
    v_first_name    employees.first_name%TYPE;
    v_last_name     employees.last_name%TYPE;
    v_email         employees.email%TYPE;
BEGIN
    -- Open the cursor
    FOR emp_rec IN (SELECT * FROM employees where EMPLOYEE_ID=100) LOOP
        -- Fetch data from the cursor
        v_employee_id := emp_rec.employee_id;
        v_first_name := emp_rec.first_name;
        v_last_name := emp_rec.last_name;
        v_email := emp_rec.email;
        -- Process or display the fetched data (you can modify this part based on your requirements)
        DBMS_OUTPUT.PUT_LINE('Employee ID: ' || v_employee_id || ', Name: ' || v_first_name || ' ' || v_last_name || ', Email: ' || v_email);
    END LOOP;

    -- Close the cursor (implicitly done when the loop finishes)
END;
/




CREATE OR REPLACE PROCEDURE get_employee_info (
    p_department_id IN employees.department_id%TYPE
)
IS
BEGIN
    FOR emp_rec IN (SELECT ROWID, last_name
                    FROM employees
                    WHERE department_id = p_department_id)
    LOOP
        DBMS_OUTPUT.PUT_LINE('ROWID: ' || emp_rec.ROWID || ', Last Name: ' || emp_rec.last_name);
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE get_employee_data_explicit_cursor IS
    -- Declare variables to hold employee data
    v_employee_id   employees.employee_id%TYPE;
    v_first_name    employees.first_name%TYPE;
    v_last_name     employees.last_name%TYPE;
    v_email         employees.email%TYPE;

    -- Declare the explicit cursor
    CURSOR employee_cursor IS
        SELECT employee_id, first_name, last_name, email
        FROM employees where EMPLOYEE_ID=100;
BEGIN
    -- Open the explicit cursor
    OPEN employee_cursor;

    -- Fetch data from the cursor
    LOOP
        FETCH employee_cursor INTO v_employee_id, v_first_name, v_last_name, v_email;

        -- Exit the loop if no more rows to fetch
        EXIT WHEN employee_cursor%NOTFOUND;

        -- Process or display the fetched data (you can modify this part based on your requirements)
        DBMS_OUTPUT.PUT_LINE('Employee ID: ' || v_employee_id || ', Name: ' || v_first_name || ' ' || v_last_name || ', Email: ' || v_email);
    END LOOP;

    -- Close the explicit cursor
    CLOSE employee_cursor;
END;
/


CREATE TABLE random_data_table (
    id          INTEGER PRIMARY KEY,
    col1        VARCHAR2(50),  -- VARCHAR in PostgreSQL
    col2        NUMBER,        -- NUMERIC in PostgreSQL
    col3        DATE,          -- DATE in PostgreSQL
    col4        CLOB           -- TEXT in PostgreSQL
);

INSERT INTO random_data_table VALUES (
    1, 'Some text', 42, NULL, 'This is a CLOB value'
);
INSERT INTO random_data_table VALUES (
    2, NULL, NULL, NULL, NULL
);
INSERT INTO random_data_table VALUES (
    3, NULL, 17, NULL, 'Another CLOB value'
);

CREATE OR REPLACE PROCEDURE process_data
AS
BEGIN
    FOR rec IN (SELECT * FROM random_data_table) LOOP
        DBMS_OUTPUT.PUT_LINE(SUBSTR(rec.col1, 0, 1));  -- Will raise issue in PostgreSQL
    END LOOP;
END;
/

CREATE SYNONYM countries_read FOR hr.countries;

create table test(idx int, txt clob);

create or replace procedure p_test(P_IDX in number,P_TXT in varchar2,P_FLAG in number) as
g_clob clob;
begin
if P_FLAG=0 then
insert into test values (P_IDX, empty_clob() ) returning txt into g_clob;
dbms_lob.write( g_clob,length(P_TXT), 1,P_TXT);
else
select txt into g_clob from test where IDX=P_IDX for update;
dbms_lob.writeappend( g_clob, length(P_TXT), P_TXT);
end if;
end;
/

drop table test;

--

-- Step 1: Create a table with range partitioning
CREATE TABLE sales (
    sale_id NUMBER,
    sale_date DATE,
    amount NUMBER
)
PARTITION BY RANGE (sale_date)
(
    PARTITION sales_january VALUES LESS THAN (TO_DATE('2024-02-01', 'YYYY-MM-DD')),
    PARTITION sales_february VALUES LESS THAN (TO_DATE('2024-03-01', 'YYYY-MM-DD')),
    PARTITION sales_march VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION sales_april VALUES LESS THAN (MAXVALUE)
);

-- Step 2: Insert sample data
INSERT INTO sales VALUES (1, TO_DATE('2024-01-15', 'YYYY-MM-DD'), 1000);
INSERT INTO sales VALUES (2, TO_DATE('2024-02-20', 'YYYY-MM-DD'), 1500);
INSERT INTO sales VALUES (3, TO_DATE('2024-03-10', 'YYYY-MM-DD'), 2000);
INSERT INTO sales VALUES (4, TO_DATE('2024-04-25', 'YYYY-MM-DD'), 1200);

-- Step 3: Query the data
SELECT * FROM sales;

-- Query data from the sales_january partition
SELECT * FROM sales PARTITION (sales_january);

-- Create a sample table
CREATE TABLE sample_table (
    id NUMBER,
    column_with_null VARCHAR2(50)
);

-- Insert some sample data
INSERT INTO sample_table VALUES (1, 'Value 1');
INSERT INTO sample_table VALUES (2, NULL);
INSERT INTO sample_table VALUES (3, 'Value 3');

-- Create the update procedure
CREATE OR REPLACE PROCEDURE update_column_value(
    p_id NUMBER,
    p_new_value VARCHAR2
) AS
BEGIN
    UPDATE sample_table
    SET column_with_null = p_new_value
    WHERE id = p_id;

    COMMIT; -- Commit the transaction
END update_column_value;
/

CREATE TABLE "DATATYPES"(
"BFILE" BFILE,
"BINARY_FLOAT" BINARY_FLOAT,
"BINARY_DOUBLE" BINARY_DOUBLE,
"BLOB" BLOB,
"CHAR" CHAR(10 BYTE),
"CHARACTER" CHAR(10 BYTE),
"CLOB" CLOB,
"NCLOB" NCLOB,
"DATE" DATE,
"DECIMAL" NUMBER(3,2),
"DEC" NUMBER(3,2),
"DOUBLE_PRECISION" FLOAT(126),
"FLOAT" FLOAT(3),
"INTEGER" NUMBER(*,0),
"INT" NUMBER(*,0),
"INTERVAL_YEAR" INTERVAL YEAR(4) TO MONTH,
"INTERVAL_DAY" INTERVAL DAY(4) TO SECOND(4),
"LONG" LONG,
"NCHAR" NCHAR(10),
"NCHAR_VARYING" NVARCHAR2(10),
"NUMBER" NUMBER(9,9),
"NUMBER1" NUMBER(9,0),
"NUMBER(*)" NUMBER,
"NUMERIC" NUMBER(9,9),
"NVARCHAR2" NVARCHAR2(10),
"RAW" RAW(10),
"REAL" FLOAT(63),
"ROW_ID" ROWID,
"SMALLINT" NUMBER(*,0),
"TIMESTAMP" TIMESTAMP(5),
"TIMESTAMP_WITH_TIME_ZONE" TIMESTAMP(5) WITH TIME ZONE,
"UROWID" UROWID(10),
"VARCHAR" VARCHAR2(10 BYTE),
"VARCHAR2" VARCHAR2(10 BYTE),
"XMLTYPE" XMLTYPE
);
